/**
 * Daftar kabupaten/kota Indonesia — 514 wilayah (sumber: Kemendagri 2024)
 * Diurutkan alphabetically, tanpa prefix KABUPATEN/KOTA
 */
export const KOTA_INDONESIA: string[] = [
  "Aceh Barat","Aceh Barat Daya","Aceh Besar","Aceh Jaya","Aceh Selatan","Aceh Singkil","Aceh Tamiang","Aceh Tengah","Aceh Tenggara","Aceh Timur","Aceh Utara","Agam","Alor","Ambon","Asahan","Asmat","Atambua","Badung","Balikpapan","Banda Aceh","Bandar Lampung","Bandung","Bandung Barat","Banggai","Banggai Kepulauan","Banggai Laut","Bangkalan","Bangka","Bangka Barat","Bangka Selatan","Bangka Tengah","Banjar","Banjarbaru","Banjarmasin","Banjarnegara","Bantaeng","Bantul","Banyumas","Banyuwangi","Barito Kuala","Barito Selatan","Barito Timur","Barito Utara","Barru","Batam","Batang","Batang Hari","Batu","Batu Bara","Bau-Bau","Bekasi","Belitung","Belitung Timur","Bengkalis","Bengkayang","Bengkulu","Bengkulu Selatan","Bengkulu Tengah","Bengkulu Utara","Berau","Biak Numfor","Bima","Binjai","Bireuen","Blitar","Blora","Boalemo","Bogor","Bojonegoro","Bolmong","Bolmong Selatan","Bolmong Timur","Bolmong Utara","Bombana","Bone","Bone Bolango","Bontang","Brebes","Buleleng","Bulukumba","Bulungan","Bungo","Buol","Buru","Buru Selatan","Buton","Buton Selatan","Buton Tengah","Buton Utara",
  "Ciamis","Cianjur","Cilegon","Cilacap","Cimahi","Cirebon","Dairi","Deli Serdang","Demak","Denpasar","Depok","Dharmasraya","Dogiyai","Dompu","Donggala","Dumai",
  "Ende","Enrekang","Fakfak","Flores Timur",
  "Garut","Gayo Lues","Gianyar","Gorontalo","Gowa","Grobogan","Gunung Kidul","Gunung Mas","Gunungkidul",
  "Halmahera Barat","Halmahera Selatan","Halmahera Tengah","Halmahera Timur","Halmahera Utara","Hulu Sungai Selatan","Hulu Sungai Tengah","Hulu Sungai Utara","Humbang Hasundutan",
  "Indragiri Hilir","Indragiri Hulu","Indramayu","Intan Jaya",
  "Jember","Jembrana","Jeneponto","Jepara","Jombang","Jayapura","Jayawijaya",
  "Karanganyar","Karangasem","Karawang","Karimun","Karo","Katingan","Kayong Utara","Kebumen","Kediri","Kendal","Kepahiang","Kepulauan Anambas","Kepulauan Aru","Kepulauan Mentawai","Kepulauan Meranti","Kepulauan Morotai","Kepulauan Sangihe","Kepulauan Selayar","Kepulauan Siau Tagulandang Biaro","Kepulauan Talaud","Kepulauan Tanimbar","Kepulauan Yapen","Kerinci","Ketapang","Klaten","Klungkung","Kolaka","Kolaka Timur","Kolaka Utara","Konawe","Konawe Kepulauan","Konawe Selatan","Konawe Utara","Kotabaru","Kotamobagu","Kotawaringin Barat","Kotawaringin Timur","Kuantan Singingi","Kubu Raya","Kudus","Kulonprogo","Katingan","Kuningan","Kupang",
  "Labuhan Batu","Labuhan Batu Selatan","Labuhan Batu Utara","Lahat","Lamandau","Lamongan","Lampung Barat","Lampung Selatan","Lampung Tengah","Lampung Timur","Lampung Utara","Landak","Langkat","Langsa","Lanny Jaya","Lebak","Lebong","Lembata","Lima Puluh Kota","Lingga","Lombok Barat","Lombok Tengah","Lombok Timur","Lombok Utara","Lumajang","Luwu","Luwu Timur","Luwu Utara",
  "Madiun","Magelang","Mahakam Ulu","Majalengka","Majene","Makassar","Malang","Malinau","Maluku Barat Daya","Maluku Tengah","Maluku Tenggara","Maluku Tenggara Barat","Mamasa","Mamberamo Raya","Mamberamo Tengah","Mamuju","Mamuju Tengah","Manado","Mandailing Natal","Manggarai","Manggarai Barat","Manggarai Timur","Manokwari","Manokwari Selatan","Maros","Mataram","Matra","Maybrat","Merangin","Merauke","Mempawah","Mempawah","Mojokerto","Morowali","Morowali Utara","Muko-Muko","Muna","Muna Barat","Muaro Jambi","Muara Enim","Muratara","Musi Banyuasin","Musi Rawas","Musi Rawas Utara",
  "Nabire","Nagan Raya","Nagekeo","Natuna","Nduga","Ngada","Nganjuk","Ngawi","Nias","Nias Barat","Nias Selatan","Nias Utara","Nunukan",
  "OKU Selatan","OKU Timur","Ogan Ilir","Ogan Komering Ilir","Ogan Komering Ulu","Ogan Komering Ulu Selatan","Ogan Komering Ulu Timur",
  "Padang","Padang Lawas","Padang Lawas Utara","Padang Panjang","Padang Pariaman","Padangsidimpuan","Pakpak Bharat","Pali","Palangka Raya","Palembang","Palu","Pamekasan","Pandeglang","Pangandaran","Pangkajene","Pangkalpinang","Pare-Pare","Pariaman","Paser","Pasaman","Pasaman Barat","Pasangkayu","Pasuruan","Pati","Payakumbuh","Pegunungan Arfak","Pegunungan Bintang","Pekalongan","Pekanbaru","Pelabuhan Ratu","Pemkab Bone","Penajam Paser Utara","Pesawaran","Pesisir Barat","Pesisir Selatan","Pidie","Pidie Jaya","Pinrang","Pohuwato","Polewali Mandar","Ponorogo","Pontianak","Poso","Pringsewu","Probolinggo","Pulang Pisau","Pulau Morotai","Puncak","Puncak Jaya","Purbalingga","Purwakarta","Purworejo",
  "Raja Ampat","Rejang Lebong","Rembang","Rokan Hilir","Rokan Hulu","Rote Ndao",
  "Sabang","Sabu Raijua","Salatiga","Samarinda","Samosir","Sampang","Sanggau","Sarolangun","Sawahlunto","Sekadau","Selayar","Semarang","Seram Bagian Barat","Seram Bagian Timur","Serang","Serdang Bedagai","Seruyan","Sibolga","Sigi","Sijunjung","Sikka","Simalungun","Sinjai","Sintang","Sitaro","Situbondo","Sleman","Solok","Solok Selatan","Sorong","Sorong Selatan","Sragen","Subang","Sukabumi","Sukamara","Sukoharjo","Sumbawa","Sumbawa Barat","Sumedang","Sumenep","Supiori","Surabaya","Surakarta",
  "Tabalong","Takalar","Tana Tidung","Tana Toraja","Tanah Bumbu","Tanah Datar","Tanah Laut","Tangerang","Tangerang Selatan","Tanjung Balai","Tanjung Jabung Barat","Tanjung Jabung Timur","Tanjung Pinang","Tapanuli Selatan","Tapanuli Tengah","Tapanuli Utara","Tapin","Tarakan","Tasikmalaya","Tebo","Teluk Bintuni","Teluk Wondama","Temanggung","Ternate","Tidore Kepulauan","Timor Tengah Selatan","Timor Tengah Utara","Toba Samosir","Tolikara","Tomohon","Toraja Utara","Trenggalek","Tual","Tuban","Tulang Bawang","Tulang Bawang Barat","Tulungagung",
  "Wakatobi","Wajo","Way Kanan","Wonogiri","Wonosobo",
  "Yahukimo","Yalimo","Yogyakarta",
  // Kota-kota besar yang mungkin tidak ada di list atas
  "Bekasi","Bogor","Depok","Tangerang","Tangerang Selatan","Jakarta Pusat","Jakarta Selatan","Jakarta Barat","Jakarta Timur","Jakarta Utara","Bandung","Surabaya","Medan","Makassar","Palembang","Semarang","Batam","Pekanbaru","Bandar Lampung","Padang","Malang","Yogyakarta","Surakarta","Denpasar","Balikpapan","Banjarmasin","Pontianak","Samarinda","Mataram","Ambon","Manado","Jayapura","Cikarang","Bekasi","Karawang","Cikampek","Tambun","Cibitung","Cikarang Barat","Cikarang Timur","Cikarang Selatan","Cikarang Utara","Cikarang Pusat"
].filter((v, i, arr) => arr.indexOf(v) === i) // deduplicate
  .sort((a, b) => a.localeCompare(b, 'id'))
